import React, { Component } from 'react';
import { Route, BrowserRouter as Router, Switch } from 'react-router-dom'

import SimCatalogNav from './components/Nav'

class App extends Component {
  render() {
    return (
      <Router>
        <div>
          <SimCatalogNav></SimCatalogNav>
          <Switch>
          </Switch>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
          <p>s</p>
        </div>
      </Router>
    );
  }
}

export default App;
